/* =====================================================================
   HUELLA DE CARBONO (HDC) - Esquema de base de datos
   Basado en el script original, con las correcciones acordadas:
   - PK con IDENTITY (excepto PROVINCIA/DISTRITO/CIUDAD que usan el id de georef)
   - CIUDAD.NOMBRE pasa de BIGINT a NVARCHAR
   - FECHA_BAJA admite NULL (registro activo = sin fecha de baja)
   - REGISTROS pasa a ser cabecera (domicilio + período) con DETALLE_REGISTRO
   - ROL_PERMISO (N:M), VEHICULO, DOMICILIO_FUENTE, REPORTE
   - COLABORA se reemplaza por COLABORACION + COLABORACION_TIPO_EMISION
   ===================================================================== */

CREATE TABLE ROL
(
    ID_ROL       BIGINT IDENTITY(1,1) NOT NULL,
    NOMBRE       NVARCHAR(200) NOT NULL,
    DESCRIPCION  NVARCHAR(500) NULL,
    ES_SISTEMA   BIT NOT NULL CONSTRAINT DF_ROL_ES_SISTEMA DEFAULT (0),
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE PERMISOS
(
    ID_PERMISO   BIGINT IDENTITY(1,1) NOT NULL,
    NOMBRE       NVARCHAR(250) NOT NULL,
    DESCRIPCION  NVARCHAR(500) NULL,
    CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UQ_PERMISOS_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE ROL_PERMISO
(
    ID_ROL       BIGINT NOT NULL,
    ID_PERMISO   BIGINT NOT NULL,
    CONSTRAINT PK_ROL_PERMISO PRIMARY KEY (ID_ROL, ID_PERMISO),
    CONSTRAINT FK_ROL_PERMISO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL) ON DELETE CASCADE,
    CONSTRAINT FK_ROL_PERMISO_PERMISO FOREIGN KEY (ID_PERMISO) REFERENCES PERMISOS (ID_PERMISO) ON DELETE CASCADE
);
GO

CREATE TABLE PROVINCIA
(
    ID_PROVINCIA BIGINT NOT NULL,
    NOMBRE       NVARCHAR(250) NOT NULL,
    CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PROVINCIA)
);
GO

CREATE TABLE DISTRITO
(
    ID_DISTRITO  BIGINT NOT NULL,
    ID_PROVINCIA BIGINT NOT NULL,
    NOMBRE       NVARCHAR(250) NOT NULL,
    CONSTRAINT PK_DISTRITO PRIMARY KEY (ID_DISTRITO),
    CONSTRAINT FK_DISTRITO_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)
);
GO

CREATE TABLE CIUDAD
(
    ID_CIUDAD    BIGINT NOT NULL,
    ID_DISTRITO  BIGINT NOT NULL,
    NOMBRE       NVARCHAR(250) NOT NULL,
    CONSTRAINT PK_CIUDAD PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_CIUDAD_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO (ID_DISTRITO)
);
GO

CREATE TABLE UNIDAD_MEDIDA
(
    ID_UNIDAD_MEDIDA BIGINT IDENTITY(1,1) NOT NULL,
    NOMBRE           NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_UNIDAD_MEDIDA PRIMARY KEY (ID_UNIDAD_MEDIDA),
    CONSTRAINT UQ_UNIDAD_MEDIDA_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE ALCANCE
(
    ID_ALCANCE   BIGINT IDENTITY(1,1) NOT NULL,
    NOMBRE       NVARCHAR(200) NOT NULL,
    DESCRIPCION  NVARCHAR(500) NULL,
    CONSTRAINT PK_ALCANCE PRIMARY KEY (ID_ALCANCE),
    CONSTRAINT UQ_ALCANCE_NOMBRE UNIQUE (NOMBRE)
);
GO

CREATE TABLE TIPO_EMISION
(
    ID_TIPO_EMISION BIGINT IDENTITY(1,1) NOT NULL,
    ID_ALCANCE      BIGINT NOT NULL,
    NOMBRE          NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_TIPO_EMISION PRIMARY KEY (ID_TIPO_EMISION),
    CONSTRAINT FK_TIPO_EMISION_ALCANCE FOREIGN KEY (ID_ALCANCE) REFERENCES ALCANCE (ID_ALCANCE)
);
GO

CREATE TABLE FUENTE_EMISION
(
    ID_FUENTE_EMISION    BIGINT IDENTITY(1,1) NOT NULL,
    ID_UNIDAD_MEDIDA     BIGINT NOT NULL,
    ID_TIPO_EMISION      BIGINT NOT NULL,
    NOMBRE               NVARCHAR(250) NOT NULL,
    VALOR_FACTOR_EMISION DECIMAL(18,6) NOT NULL,
    FECHA_ALTA           SMALLDATETIME NOT NULL CONSTRAINT DF_FUENTE_FECHA_ALTA DEFAULT (GETDATE()),
    FECHA_BAJA           SMALLDATETIME NULL,
    FECHA_MODIFICACION   SMALLDATETIME NULL,
    CONSTRAINT PK_FUENTE_EMISION PRIMARY KEY (ID_FUENTE_EMISION),
    CONSTRAINT FK_FUENTE_UNIDAD FOREIGN KEY (ID_UNIDAD_MEDIDA) REFERENCES UNIDAD_MEDIDA (ID_UNIDAD_MEDIDA),
    CONSTRAINT FK_FUENTE_TIPO FOREIGN KEY (ID_TIPO_EMISION) REFERENCES TIPO_EMISION (ID_TIPO_EMISION),
    CONSTRAINT CK_FUENTE_FACTOR CHECK (VALOR_FACTOR_EMISION >= 0)
);
GO

CREATE TABLE USUARIO
(
    ID_USUARIO   BIGINT IDENTITY(1,1) NOT NULL,
    ID_ROL       BIGINT NOT NULL,
    EMAIL        NVARCHAR(100) NOT NULL,
    CONTRASENA   NVARCHAR(250) NOT NULL,
    TELEFONO     VARCHAR(30) NULL,
    FECHA_ALTA   SMALLDATETIME NOT NULL CONSTRAINT DF_USUARIO_FECHA_ALTA DEFAULT (GETDATE()),
    FECHA_BAJA   SMALLDATETIME NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);
GO

CREATE TABLE INDIVIDUO
(
    ID_USUARIO       BIGINT NOT NULL,
    NOMBRES          NVARCHAR(200) NOT NULL,
    APELLIDOS        NVARCHAR(250) NOT NULL,
    DNI              VARCHAR(10) NOT NULL,
    FECHA_NACIMIENTO DATE NULL,
    GENERO           NVARCHAR(30) NULL,
    CONSTRAINT PK_INDIVIDUO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_INDIVIDUO_DNI UNIQUE (DNI),
    CONSTRAINT FK_INDIVIDUO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE
);
GO

CREATE TABLE ORGANIZACION
(
    ID_USUARIO        BIGINT NOT NULL,
    RAZON_SOCIAL      NVARCHAR(250) NOT NULL,
    CUIT              VARCHAR(13) NOT NULL,
    AREA              NVARCHAR(100) NOT NULL,
    DESCRIPCION       NVARCHAR(1000) NULL,
    CANTIDAD_MIEMBROS INT NULL,
    CONSTRAINT PK_ORGANIZACION PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_ORGANIZACION_CUIT UNIQUE (CUIT),
    CONSTRAINT FK_ORGANIZACION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CK_ORGANIZACION_MIEMBROS CHECK (CANTIDAD_MIEMBROS IS NULL OR CANTIDAD_MIEMBROS >= 0)
);
GO

CREATE TABLE VEHICULO
(
    ID_VEHICULO      BIGINT IDENTITY(1,1) NOT NULL,
    ID_USUARIO       BIGINT NOT NULL,
    TIPO_VEHICULO    NVARCHAR(20) NOT NULL,
    MARCA            NVARCHAR(100) NOT NULL,
    MODELO           NVARCHAR(100) NOT NULL,
    PATENTE          VARCHAR(10) NOT NULL,
    TIPO_COMBUSTIBLE NVARCHAR(20) NOT NULL,
    TIPO_USO         NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_VEHICULO PRIMARY KEY (ID_VEHICULO),
    CONSTRAINT FK_VEHICULO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CK_VEHICULO_TIPO CHECK (TIPO_VEHICULO IN (N'Auto', N'Motocicleta', N'Camioneta', N'Camión')),
    CONSTRAINT CK_VEHICULO_COMBUSTIBLE CHECK (TIPO_COMBUSTIBLE IN (N'Nafta', N'Gasoil', N'GNC')),
    CONSTRAINT CK_VEHICULO_USO CHECK (TIPO_USO IN (N'Personal', N'Institucional'))
);
GO

CREATE TABLE DOMICILIO
(
    ID_DOMICILIO  BIGINT IDENTITY(1,1) NOT NULL,
    ID_CIUDAD     BIGINT NOT NULL,
    ID_USUARIO    BIGINT NOT NULL,
    CALLE         NVARCHAR(200) NOT NULL,
    NUMERO        INT NOT NULL,
    DEPARTAMENTO  NVARCHAR(20) NULL,
    PISO          NVARCHAR(20) NULL,
    BLOCK         NVARCHAR(20) NULL,
    MANZANA       NVARCHAR(20) NULL,
    CODIGO_POSTAL NVARCHAR(15) NOT NULL,
    TELEFONO      VARCHAR(30) NULL,
    FECHA_ALTA    SMALLDATETIME NOT NULL CONSTRAINT DF_DOMICILIO_FECHA_ALTA DEFAULT (GETDATE()),
    FECHA_BAJA    SMALLDATETIME NULL,
    TOTAL_KG_CO2  DECIMAL(18,6) NOT NULL CONSTRAINT DF_DOMICILIO_TOTAL DEFAULT (0),
    CONSTRAINT PK_DOMICILIO PRIMARY KEY (ID_DOMICILIO),
    CONSTRAINT FK_DOMICILIO_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD (ID_CIUDAD),
    CONSTRAINT FK_DOMICILIO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
GO

/* Fuentes de emisión habituales de un domicilio (se precargan al crear un registro) */
CREATE TABLE DOMICILIO_FUENTE
(
    ID_DOMICILIO      BIGINT NOT NULL,
    ID_FUENTE_EMISION BIGINT NOT NULL,
    CONSTRAINT PK_DOMICILIO_FUENTE PRIMARY KEY (ID_DOMICILIO, ID_FUENTE_EMISION),
    CONSTRAINT FK_DOMFUENTE_DOMICILIO FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO (ID_DOMICILIO) ON DELETE CASCADE,
    CONSTRAINT FK_DOMFUENTE_FUENTE FOREIGN KEY (ID_FUENTE_EMISION) REFERENCES FUENTE_EMISION (ID_FUENTE_EMISION)
);
GO

/* Cabecera del registro de emisiones: un domicilio en un período (mes) */
CREATE TABLE REGISTROS
(
    ID_REGISTRO               BIGINT IDENTITY(1,1) NOT NULL,
    ID_DOMICILIO              BIGINT NOT NULL,
    ID_USUARIO_CARGA          BIGINT NOT NULL,
    PERIODO                   DATE NOT NULL,
    OBSERVACIONES             NVARCHAR(500) NULL,
    TOTAL_KG_CO2              DECIMAL(18,6) NOT NULL CONSTRAINT DF_REGISTROS_TOTAL DEFAULT (0),
    FECHA_CREACION            DATETIME NOT NULL CONSTRAINT DF_REGISTROS_CREACION DEFAULT (GETDATE()),
    FECHA_ULTIMA_MODIFICACION DATETIME NOT NULL CONSTRAINT DF_REGISTROS_MODIF DEFAULT (GETDATE()),
    CONSTRAINT PK_REGISTROS PRIMARY KEY (ID_REGISTRO),
    CONSTRAINT FK_REGISTROS_DOMICILIO FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO (ID_DOMICILIO),
    CONSTRAINT FK_REGISTROS_USUARIO_CARGA FOREIGN KEY (ID_USUARIO_CARGA) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_REGISTROS_PERIODO CHECK (DAY(PERIODO) = 1)
);
GO

CREATE INDEX IX_REGISTROS_DOMICILIO_PERIODO ON REGISTROS (ID_DOMICILIO, PERIODO);
GO

/* Detalle: cada consumo de una fuente de emisión dentro del registro */
CREATE TABLE DETALLE_REGISTRO
(
    ID_DETALLE           BIGINT IDENTITY(1,1) NOT NULL,
    ID_REGISTRO          BIGINT NOT NULL,
    ID_FUENTE_EMISION    BIGINT NOT NULL,
    CONSUMO              DECIMAL(18,4) NOT NULL,
    VALOR_FACTOR_EMISION DECIMAL(18,6) NOT NULL,
    KG_CO2               DECIMAL(18,6) NOT NULL,
    CONSTRAINT PK_DETALLE_REGISTRO PRIMARY KEY (ID_DETALLE),
    CONSTRAINT FK_DETALLE_REGISTRO FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS (ID_REGISTRO) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_FUENTE FOREIGN KEY (ID_FUENTE_EMISION) REFERENCES FUENTE_EMISION (ID_FUENTE_EMISION),
    CONSTRAINT CK_DETALLE_CONSUMO CHECK (CONSUMO > 0)
);
GO

/* Colaboración: el titular del domicilio invita a otro usuario a cargar
   emisiones de ciertos tipos durante un rango de períodos */
CREATE TABLE COLABORACION
(
    ID_COLABORACION        BIGINT IDENTITY(1,1) NOT NULL,
    ID_DOMICILIO           BIGINT NOT NULL,
    ID_USUARIO_COLABORADOR BIGINT NOT NULL,
    PERIODO_DESDE          DATE NOT NULL,
    PERIODO_HASTA          DATE NULL,
    ESTADO                 VARCHAR(20) NOT NULL CONSTRAINT DF_COLABORACION_ESTADO DEFAULT ('PENDIENTE'),
    MENSAJE                NVARCHAR(500) NULL,
    FECHA_INVITACION       DATETIME NOT NULL CONSTRAINT DF_COLABORACION_FECHA DEFAULT (GETDATE()),
    FECHA_RESPUESTA        DATETIME NULL,
    CONSTRAINT PK_COLABORACION PRIMARY KEY (ID_COLABORACION),
    CONSTRAINT FK_COLABORACION_DOMICILIO FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO (ID_DOMICILIO) ON DELETE CASCADE,
    CONSTRAINT FK_COLABORACION_USUARIO FOREIGN KEY (ID_USUARIO_COLABORADOR) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT CK_COLABORACION_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'REVOCADA')),
    CONSTRAINT CK_COLABORACION_PERIODOS CHECK (PERIODO_HASTA IS NULL OR PERIODO_HASTA >= PERIODO_DESDE)
);
GO

CREATE TABLE COLABORACION_TIPO_EMISION
(
    ID_COLABORACION BIGINT NOT NULL,
    ID_TIPO_EMISION BIGINT NOT NULL,
    CONSTRAINT PK_COLABORACION_TIPO PRIMARY KEY (ID_COLABORACION, ID_TIPO_EMISION),
    CONSTRAINT FK_COLABTIPO_COLABORACION FOREIGN KEY (ID_COLABORACION) REFERENCES COLABORACION (ID_COLABORACION) ON DELETE CASCADE,
    CONSTRAINT FK_COLABTIPO_TIPO FOREIGN KEY (ID_TIPO_EMISION) REFERENCES TIPO_EMISION (ID_TIPO_EMISION)
);
GO

/* Reporte guardado: conserva los filtros para volver a generarlo */
CREATE TABLE REPORTE
(
    ID_REPORTE     BIGINT IDENTITY(1,1) NOT NULL,
    ID_USUARIO     BIGINT NOT NULL,
    NOMBRE         NVARCHAR(200) NOT NULL,
    DESCRIPCION    NVARCHAR(500) NULL,
    FILTROS        NVARCHAR(MAX) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL CONSTRAINT DF_REPORTE_FECHA DEFAULT (GETDATE()),
    CONSTRAINT PK_REPORTE PRIMARY KEY (ID_REPORTE),
    CONSTRAINT FK_REPORTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE
);
GO
